#pragma once

static spritesheet_t g_Items_SpriteSheet = {
    .name   = "./res/icons/spritesheet.png",
    .offset = {
        {
            .frame = "bad_dog",
            .x_offset = 0,
            .y_offset = 4 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "coca_cola",
            .x_offset = 3 * 64,
            .y_offset = 4 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "pepsi",
            .x_offset = 1 * 64,
            .y_offset = 2 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "sprite",
            .x_offset = 1 * 64,
            .y_offset = 3 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "fanta_orange",
            .x_offset = 2 * 64,
            .y_offset = 0,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "mountain_dew",
            .x_offset = 3 * 64,
            .y_offset = 1 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "dr_pepper",
            .x_offset = 1 * 64,
            .y_offset = 0 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "red_bull",
            .x_offset = 0,
            .y_offset = 3 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "monster_energy",
            .x_offset = 2 * 64,
            .y_offset = 1 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "water_bottle",
            .x_offset = 3 * 64,
            .y_offset = 3 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "iced_tea",
            .x_offset = 0,
            .y_offset = 1 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "orange_juice",
            .x_offset = 0,
            .y_offset = 2 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame = "chocolate_bar",
            .x_offset = 2 * 64,
            .y_offset = 4 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "potato_chips",
            .x_offset = 2 * 64,
            .y_offset = 2 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "gummy_bears",
            .x_offset = 3 * 64,
            .y_offset = 0,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "cookies",
            .x_offset = 0,
            .y_offset = 0,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "protein_bar",
            .x_offset = 3 * 64,
            .y_offset = 2 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "trail_mix",
            .x_offset = 2 * 64,
            .y_offset = 3 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "chewing_gum",
            .x_offset = 1 * 64,
            .y_offset = 4 * 64,
            .width    = 64,
            .height   = 64,
        },
        {
            .frame     = "mints",
            .x_offset = 1 * 64,
            .y_offset = 1 * 64,
            .width    = 64,
            .height   = 64,
        },
    },
    .offset_count = 20
};
